### PR TITLE
Update alpine to 3.8

### PR DESCRIPTION
**Pull request by marians**
For https://github.com/giantswarm/giantswarm/issues/4197

### CODE REVIEW

**Comment by marians** [comment]
Hmm. No CI checks? That doesn't fill me with confidence... ;-)

**Comment by webwurst** [comment]
We can also archive this since the upstream project isn't maintained anymore: https://github.com/bitly/oauth2_proxy/issues/628#issuecomment-417121636

**Comment by marians** [comment]
Which repo is the oauth proxy then which we have in use?

**Comment by marians** [comment]
@webwurst Which repo is the oauth proxy then which we have in use?

**Comment by indyfree** [comment]
@marians We are using a prebuild image from a bitly fork that doesn't use alpine. See here: https://github.com/giantswarm/g8s-oauth2-proxy/blob/e5b102d5ebf46d3f1ddab06dce9a2a9eb89a3cfc/helm/g8s-oauth2-proxy-chart/templates/deployment.yaml#L22

IMO this repo can be archived.

**Pull request closed without merging**
